### ISSUE TITLE
grabber.png incorrect path

### ISSUE THREAD

**Issue by barrykooij** [barrykooij/related-posts-for-wp#101]
https://github.com/barrykooij/related-posts-for-wp/blob/master/assets/css/edit-post.css

```
.rp4wp_table_manage.sortable tr{cursor:move}.rp4wp_table_manage.sortable tr td{background-position:98% 50%;background-image:url(../../images/grabber.png);background-repeat:no-repeat}.rp4wp_table_manage td{padding-bottom:11px}.rp4wp_table_manage tr:nth-child(odd){background-color:#FCFCFC}.rp4wp_button_holder{padding:10px 0;float:right}.rp4wp_button_holder span{margin-left:10px;float:left}.rp4wp_save_button{float:right}.rp4wp_ajaxloader{height:13px;margin-left:10px}
```

Image is only 1 map up.

**Comment by finalwebsites** [comment]
Hi Barry,
is this bug back again of just not yet solved ;)

![screenshot 2018-08-17 at 13 54 24](https://user-images.githubusercontent.com/90638/44265098-8265cf00-a225-11e8-9478-57a93bffeb4d.png)

PS. the path is correct for the edit-post.scss file btw
