### ISSUE TITLE
WP CLI support

### ISSUE THREAD

**Issue by cinghaman** [barrykooij/related-posts-for-wp#104]
Is there a way to have WP CLI support to set up linking of articles, as I have more then 9000+ articles and it is taking ages to link them and if I close the window or internet breaks in between, it will need to be restarted again.

Thanks

**Comment by hchouhan** [comment]
@barrykooij can you please look into this?

**Comment by hchouhan** [comment]
https://secure.helpscout.net/conversation/1352983638/12861

**Comment by barrykooij** [comment]
WP-CLI is supported in our premium version. Please see all differences here: https://www.relatedpostsforwp.com/upgrade-premium/
