### ISSUE TITLE
Knowing which related posts have been linked manually

### ISSUE THREAD

**Issue by lvvvvvl** [barrykooij/related-posts-for-wp#105]
Hello,

I'm currently auditing my top 100 posts and manually linking the related posts for greater accuracy. However, I noticed there's no way of knowing which posts I've previously linked to manually and which ones we're automatically linked by the plugin.

It would be helpful having some sort of symbol/label so I know which ones have already been done so as to prevent losing them every time I relink all posts (they posts currently related may be relevant but then after a new relinking, may be linked to not so relevant posts).

Thank you.

**Comment by barrykooij** [comment]
This is actually a feature of the premium version, see all differences here: https://www.relatedpostsforwp.com/upgrade-premium/
