### ISSUE TITLE
long running database queries

### ISSUE THREAD

**Issue by dws122** [barrykooij/related-posts-for-wp#106]
Using New Relic to monitor a large, high volume site with approximately 70,000 posts.

![Screen Shot on 2019-08-28 at 21-34-31](https://user-images.githubusercontent.com/12969150/63903815-de3c6980-c9dc-11e9-80ce-1d821f54783c.png)

These long-running queries appear to happen very close in time to when a new post is saved.

Any ideas? Anything I can check or additional information you need?

**Comment by barrykooij** [comment]
These are the queries that find related posts once when a new post is added / published to your website. We do the heavy lifting once on post creation, so we don't have to query on page load.
