### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [barrykooij/related-posts-for-wp#110]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@foobar7) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by barrykooij** [comment]
Hey there!

You can email me at support@relatedpostsforwp.com

Thank you!

**Comment by barrykooij** [comment]
I'll also add the `SECURITY.md` soon

**Comment by barrykooij** [comment]
`SECURITY.md` file now also added https://github.com/barrykooij/related-posts-for-wp/blob/master/SECURITY.md

**Comment by barrykooij** [comment]
Also, reported vulnerability is fixed in version 2.1.2
