### ISSUE TITLE
Encoding issue with Chinese text

### ISSUE THREAD

**Issue by barrykooij** [barrykooij/related-posts-for-wp#62]
My site's in Chinese, so i'm looking in mysql, and under wp_rp4wp_cache it's just all "???????????????????????????????????????"

https://wordpress.org/support/topic/related-posts-on-all-pages-is-the-same

**Comment by clammy77** [comment]
Hi, yeah, is there any way to fix this? dying to get this to work.

**Comment by barrykooij** [comment]
@clammy77 Could you upload some dummy content that is failing for you?

**Comment by barrykooij** [comment]
@clammy77 This is fixed and will be released soon! :)
