### ISSUE TITLE
Unable to update with the line updater

### ISSUE THREAD

**Issue by SiR-DanieL** [barrykooij/related-posts-for-wp#70]
Seems that this plugin (at least the Premium version) is not compatible with the new line updater. As soon as i click "Update" nothing happens.

![](http://cld.wthms.co/NaZl/2lB7VpDp+)

**Comment by barrykooij** [comment]
@SiR-DanieL click 'update' in the plugins screen?

**Comment by SiR-DanieL** [comment]
Exactly

Il giorno ven 19 giu 2015 15:35 Barry Kooij <notifications@github.com> ha
scritto:

**Comment by barrykooij** [comment]
@SiR-DanieL this should be fixed, can you confirm?

**Comment by SiR-DanieL** [comment]
I confirm! Thanks
