### ISSUE TITLE
Posts with no featured image

### ISSUE THREAD

**Issue by jaredatch** [barrykooij/related-posts-for-wp#72]
Is there a recommended way to handle this?

Ideally either;

1 - Option to not include posts with no featured image
2 - Be able to filter a default image for posts with no feature image

Thoughts or insight?

**Comment by barrykooij** [comment]
I've been thinking about implementing 2 for some time. I'll look into this soon.
Thanks for reporting.

**Comment by jaredatch** [comment]
Let me know if you've given then any more thought. Plaguing a site I'm working with right now.

http://cl.ly/image/0F422V2b3C3n

**Comment by barrykooij** [comment]
So this was eventually implemented in the premium version. We might add this in the free version some day but there are no plans for doing this now.

If you want to chat this over more, please don't hesitate to contact us via never5.com/#contact
