### ISSUE TITLE
Increase weight for words inside heading elements.

### ISSUE THREAD

**Issue by dannyvankooten** [barrykooij/related-posts-for-wp#75]
Something like this would be cool and would be great for increased relevancy between posts.

``` php
$heading_weight = 1; // <h1>
$word_amount = $word_amount * ( 6 - $heading_weight )
```

**Comment by barrykooij** [comment]
This was added somewhere between creation and now :)

https://github.com/barrykooij/related-posts-for-wp/blob/master/classes/class-related-word-manager.php#L243
