### ISSUE TITLE
Improve performance for building word cache.

### ISSUE THREAD

**Issue by dannyvankooten** [barrykooij/related-posts-for-wp#81]
See #76 #77 #78 #79 #80 .

I used Blackfire + their PHP SDK to benchmark just the `RP4WP_Hook_Ajax_Install_Save_Words::run` method, so this is as accurate as it gets.

This was with 200 FakerPress posts, on PHP 5.6.

**Before**
![image](https://cloud.githubusercontent.com/assets/885856/12534966/62fa4e2a-c2a3-11e5-8361-dc3ce774b683.png)

**After**
![image](https://cloud.githubusercontent.com/assets/885856/12534968/6a123100-c2a3-11e5-8398-c3c21c31e6dc.png)

**Comment by barrykooij** [comment]
Thanks so much for this mate. All merged.
