### ISSUE TITLE
Search Term - Combining multiple words

### ISSUE THREAD

**Issue by mblavos** [barrykooij/related-posts-for-wp#86]
The search box is combining multiple words into one word. Because of this, no results are displayed.

1.  Click "Add Related Posts" while editing a post
2. Choose "All Posts"
3. Search for "city tour"
4. Observe the Search Bar refreshed to "citytour" and no results displayed. Expected to see results for two words "city tour."

**Comment by barrykooij** [comment]
Confirmed. We fixed this in premium the other day, will fix this in this repository soon.

Thanks for reporting.

**Comment by mblavos** [comment]
Any updates on when this will be included?

**Comment by barrykooij** [comment]
Just fixed this. Will be included in the 2.0 release. Thank you for your patience.
