### ISSUE TITLE
Related Posts for WordPress text squished on smaller screen

### ISSUE THREAD

**Issue by paaljoachim** [barrykooij/related-posts-for-wp#91]
http://test1.dev/wp-admin/options-general.php?page=rp4wp_configurator

![screen shot 2016-10-03 at 19 15 55](https://cloud.githubusercontent.com/assets/5323259/19057442/db670800-899d-11e6-85f0-9610bfbfa051.png)

Making the screen smaller this happens:

![screen shot 2016-10-03 at 19 16 02](https://cloud.githubusercontent.com/assets/5323259/19057445/e2861068-899d-11e6-85ce-2ddfbb890742.png)

(It is on the pro version you sent me which I am now testing.)

**Comment by barrykooij** [comment]
Thanks for reporting! Will look into this.

**Comment by barrykooij** [comment]
This is a premium issue, moving it to private repo.
