### ISSUE TITLE
Not updated when post is deleted?

### ISSUE THREAD

**Issue by inrgb** [barrykooij/related-posts-for-wp#96]
When deleting a post it still exists in other posts related posts...

So you get this on the backend:
Trying to get property of non-object in /Applications/MAMP/htdocs/afc/wp-content/plugins/related-posts-for-wp-premium/classes/meta-boxes/class-meta-box-manage.php on line 95

This should hook into when a post is deleted and remove it from related posts.

**Comment by barrykooij** [comment]
Correct. I've just fixed this in the premium version. Looking into fixing/implementing this in the free version.

**Comment by barrykooij** [comment]
Correction. This was already fixed in 2.0.0 :)
